//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                role: {
                    name: "role",
                    type: "Role",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("USER") }] }],
                    default: "USER"
                },
                submissions: {
                    name: "submissions",
                    type: "Submission",
                    array: true,
                    relation: { opposite: "user" }
                },
                leaderboard: {
                    name: "leaderboard",
                    type: "Leaderboard",
                    array: true,
                    relation: { opposite: "user" }
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                magicLinks: {
                    name: "magicLinks",
                    type: "MagicLinkToken",
                    array: true,
                    relation: { opposite: "user" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Challenge: {
            name: "Challenge",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                title: {
                    name: "title",
                    type: "String"
                },
                notionDocId: {
                    name: "notionDocId",
                    type: "String"
                },
                maxPoints: {
                    name: "maxPoints",
                    type: "Int"
                },
                submissions: {
                    name: "submissions",
                    type: "Submission",
                    array: true,
                    relation: { opposite: "challenge" }
                },
                contests: {
                    name: "contests",
                    type: "ContestProblem",
                    array: true,
                    relation: { opposite: "challenge" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Contest: {
            name: "Contest",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                title: {
                    name: "title",
                    type: "String"
                },
                startTime: {
                    name: "startTime",
                    type: "DateTime"
                },
                endTime: {
                    name: "endTime",
                    type: "DateTime"
                },
                isRated: {
                    name: "isRated",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                problems: {
                    name: "problems",
                    type: "ContestProblem",
                    array: true,
                    relation: { opposite: "contest" }
                },
                submissions: {
                    name: "submissions",
                    type: "Submission",
                    array: true,
                    relation: { opposite: "contest" }
                },
                leaderboard: {
                    name: "leaderboard",
                    type: "Leaderboard",
                    array: true,
                    relation: { opposite: "contest" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        ContestProblem: {
            name: "ContestProblem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                challengeId: {
                    name: "challengeId",
                    type: "String",
                    foreignKeyFor: [
                        "challenge"
                    ]
                },
                contestId: {
                    name: "contestId",
                    type: "String",
                    foreignKeyFor: [
                        "contest"
                    ]
                },
                index: {
                    name: "index",
                    type: "Int"
                },
                contest: {
                    name: "contest",
                    type: "Contest",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "problems", fields: ["contestId"], references: ["id"], onDelete: "Cascade" }
                },
                challenge: {
                    name: "challenge",
                    type: "Challenge",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("challengeId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "contests", fields: ["challengeId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId"), ExpressionUtils.field("challengeId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                contestId_challengeId: { contestId: { type: "String" }, challengeId: { type: "String" } }
            }
        },
        Submission: {
            name: "Submission",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                challengeId: {
                    name: "challengeId",
                    type: "String",
                    foreignKeyFor: [
                        "challenge"
                    ]
                },
                contestId: {
                    name: "contestId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "contest"
                    ]
                },
                code: {
                    name: "code",
                    type: "String"
                },
                language: {
                    name: "language",
                    type: "String"
                },
                status: {
                    name: "status",
                    type: "SubmissionStatus"
                },
                points: {
                    name: "points",
                    type: "Int"
                },
                executionTime: {
                    name: "executionTime",
                    type: "Float"
                },
                memoryUsed: {
                    name: "memoryUsed",
                    type: "Float",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "submissions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                challenge: {
                    name: "challenge",
                    type: "Challenge",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("challengeId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "submissions", fields: ["challengeId"], references: ["id"], onDelete: "Cascade" }
                },
                contest: {
                    name: "contest",
                    type: "Contest",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "submissions", fields: ["contestId"], references: ["id"], onDelete: "Cascade" }
                },
                plagiarismReports: {
                    name: "plagiarismReports",
                    type: "PlagiarismReport",
                    array: true,
                    relation: { opposite: "submission" }
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("challengeId")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Leaderboard: {
            name: "Leaderboard",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                contestId: {
                    name: "contestId",
                    type: "String",
                    foreignKeyFor: [
                        "contest"
                    ]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                solved: {
                    name: "solved",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                penalty: {
                    name: "penalty",
                    type: "Int",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }],
                    default: 0
                },
                contest: {
                    name: "contest",
                    type: "Contest",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "leaderboard", fields: ["contestId"], references: ["id"], onDelete: "Cascade" }
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "leaderboard", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contestId"), ExpressionUtils.field("userId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                contestId_userId: { contestId: { type: "String" }, userId: { type: "String" } }
            }
        },
        PlagiarismReport: {
            name: "PlagiarismReport",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                submissionId: {
                    name: "submissionId",
                    type: "String",
                    foreignKeyFor: [
                        "submission"
                    ]
                },
                matchedWithId: {
                    name: "matchedWithId",
                    type: "String",
                    optional: true
                },
                similarityScore: {
                    name: "similarityScore",
                    type: "Float"
                },
                status: {
                    name: "status",
                    type: "PlagiarismStatus",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("PENDING") }] }],
                    default: "PENDING"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                submission: {
                    name: "submission",
                    type: "Submission",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("submissionId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "plagiarismReports", fields: ["submissionId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("submissionId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        MagicLinkToken: {
            name: "MagicLinkToken",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                email: {
                    name: "email",
                    type: "String"
                },
                tokenHash: {
                    name: "tokenHash",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                usedAt: {
                    name: "usedAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("SetNull") }] }],
                    relation: { opposite: "magicLinks", fields: ["userId"], references: ["id"], onDelete: "SetNull" }
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("email")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("DateTime", [ExpressionUtils.field("expiresAt")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                tokenHash: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                tokenHash: {
                    name: "tokenHash",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                revokedAt: {
                    name: "revokedAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }] },
                { name: "@@index", args: [{ name: "fields", value: ExpressionUtils.array("DateTime", [ExpressionUtils.field("expiresAt")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                tokenHash: { type: "String" }
            }
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                USER: "USER",
                ADMIN: "ADMIN"
            }
        },
        SubmissionStatus: {
            name: "SubmissionStatus",
            values: {
                QUEUED: "QUEUED",
                RUNNING: "RUNNING",
                ACCEPTED: "ACCEPTED",
                WRONG_ANSWER: "WRONG_ANSWER",
                TLE: "TLE",
                RUNTIME_ERROR: "RUNTIME_ERROR",
                MEMORY_LIMIT: "MEMORY_LIMIT"
            }
        },
        PlagiarismStatus: {
            name: "PlagiarismStatus",
            values: {
                PENDING: "PENDING",
                CONFIRMED: "CONFIRMED",
                REJECTED: "REJECTED"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
